<?php 
$this->headScript()->appendFile('/resources/javascript/highcharts/js/highcharts.js', 'text/javascript');
$this->headScript()->appendFile('/resources/javascript/strophejs/strophe.min.js', 'text/javascript');
$this->headScript()->appendFile('/resources/javascript/example/statistic.js', 'text/javascript');
$options = array(
	'service' => array(
		'url' => '/bind',
		'domain' => $this->xmppConfig['domain'],
		'username' => 'demo1',
		'password' => 'demo1'
	),
	'chartData' => $this->chartData
);
$this->placeholder('onready')->captureStart('APPEND');
?>
var statisticObj = new Statistic(<?php echo json_encode($options);?>);
<?php 
$this->placeholder('onready')->captureEnd();
?>
<h2>Statistic</h2>
<div id="chart"></div>